name: Hourly Trigger
on:
  schedule:
    - cron: '0 * * * *'

permissions:
  actions: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Permit Monitor
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: monitor.yml
          token: ${{ secrets.GITHUB_TOKEN }}
